# Generated by Django 2.1.1 on 2021-05-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djoba', '0003_auto_20210526_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsearch',
            name='date_ended',
            field=models.DateField(null=True),
        ),
    ]
