# Generated by Django 2.1.1 on 2021-05-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djoba', '0004_auto_20210526_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsearch',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default=2, max_length=10),
            preserve_default=False,
        ),
    ]
