# Generated by Django 2.1.1 on 2021-05-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djoba', '0005_jobsearch_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsearch',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10),
        ),
    ]
